const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost/lcn/treatment_nd_test.php?id=2#termin',{waitUntil:'domcontentloaded'});
assert.equal(await p.locator('#ueberblick [name=duration]').count(),0);assert.equal(await p.locator('#termin [name=duration]').count(),1);assert.equal(await p.locator('#termin [name=dose]').count(),1);assert.equal(await p.locator('#wirkung .nd-symptom-group').count()>0,true);assert.equal(await p.locator('.nd-provider-map').count(),3);
assert.equal(await p.locator('[data-distribution-percent=duration_band]').first().innerText(),'90 %');await p.locator('[name=duration_band]').first().check();await p.locator('#nd-demo-header-toggle').click();assert.equal(await p.locator('[data-distribution-percent=duration_band]').first().innerText(),'–');assert.ok(await p.locator('[name=duration_band]').first().isChecked());
await p.locator('#termin .nd-map-canvas.leaflet-container').waitFor({timeout:25000});assert.ok(await p.locator('#termin .nd-map-results li').count()>0);
assert.ok(await p.locator('#termin .leaflet-top.leaflet-right .leaflet-control-zoom').count());assert.ok(await p.locator('#termin img.leaflet-marker-icon').count());await p.locator('#termin .top-map-header').click();assert.equal(await p.locator('#termin .nd-map-canvas').isVisible(),false);await p.locator('#termin .top-map-header').click();assert.equal(await p.locator('#termin .nd-map-canvas').isVisible(),true);
await p.route('**/api/geocode_location.php?*',route=>route.fulfill({json:{ok:true,result:{lat:51.96,lng:7.63,formatted:'Münster (Testort)'}}}));await p.locator('#termin .nd-map-location input').fill('Münster');await p.locator('#termin .nd-map-location button[type=submit]').click();await p.waitForFunction(()=>document.querySelector('#termin .nd-map-results').textContent.includes('km Luftlinie'));assert.match(await p.locator('#ueberblick .nd-map-results').innerText(),/km Luftlinie/);
await p.locator('a[data-view=ueberblick]').click();await p.locator('#ueberblick .nd-map-canvas').scrollIntoViewIfNeeded();await p.waitForTimeout(1500);await p.screenshot({path:process.env.TEMP+'/nd-map-new.png'});await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('a[data-view=termin]').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS: moved timing/medicine, symptom tab4, four dummy scales and input preservation, real map markers, shared distances (mock geocoder), mobile.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});

