-- Add independent country-specific billing contexts; preserve historical votes.
INSERT INTO doctor_community_options(question_key,context_key,option_value,label) VALUES
('costs','de-self',1,'Komplett übernommen'),
('costs','de-self',2,'Bis 100 €'),
('costs','de-self',3,'Mehrere 100 €'),
('costs','de-self',4,'Mehrere 1.000 €'),
('costs','de-self',5,'10.000 € oder mehr'),
('costs','de-self',6,'Mehrere 10.000 €'),
('costs','de-abroad',1,'Komplett übernommen'),
('costs','de-abroad',2,'Bis 100 €'),
('costs','de-abroad',3,'Mehrere 100 €'),
('costs','de-abroad',4,'Mehrere 1.000 €'),
('costs','de-abroad',5,'10.000 € oder mehr'),
('costs','de-abroad',6,'Mehrere 10.000 €'),
('costs','at-public',1,'Komplett übernommen'),
('costs','at-public',2,'Bis 100 €'),
('costs','at-public',3,'Mehrere 100 €'),
('costs','at-public',4,'Mehrere 1.000 €'),
('costs','at-public',5,'10.000 € oder mehr'),
('costs','at-public',6,'Mehrere 10.000 €'),
('costs','at-elective',1,'Komplett übernommen'),
('costs','at-elective',2,'Bis 100 €'),
('costs','at-elective',3,'Mehrere 100 €'),
('costs','at-elective',4,'Mehrere 1.000 €'),
('costs','at-elective',5,'10.000 € oder mehr'),
('costs','at-elective',6,'Mehrere 10.000 €'),
('costs','at-private',1,'Komplett übernommen'),
('costs','at-private',2,'Bis 100 €'),
('costs','at-private',3,'Mehrere 100 €'),
('costs','at-private',4,'Mehrere 1.000 €'),
('costs','at-private',5,'10.000 € oder mehr'),
('costs','at-private',6,'Mehrere 10.000 €'),
('costs','at-abroad',1,'Komplett übernommen'),
('costs','at-abroad',2,'Bis 100 €'),
('costs','at-abroad',3,'Mehrere 100 €'),
('costs','at-abroad',4,'Mehrere 1.000 €'),
('costs','at-abroad',5,'10.000 € oder mehr'),
('costs','at-abroad',6,'Mehrere 10.000 €'),
('costs','ch-basic',1,'Komplett übernommen'),
('costs','ch-basic',2,'Bis 100 CHF'),
('costs','ch-basic',3,'Mehrere 100 CHF'),
('costs','ch-basic',4,'Mehrere 1.000 CHF'),
('costs','ch-basic',5,'10.000 CHF oder mehr'),
('costs','ch-basic',6,'Mehrere 10.000 CHF'),
('costs','ch-extra',1,'Komplett übernommen'),
('costs','ch-extra',2,'Bis 100 CHF'),
('costs','ch-extra',3,'Mehrere 100 CHF'),
('costs','ch-extra',4,'Mehrere 1.000 CHF'),
('costs','ch-extra',5,'10.000 CHF oder mehr'),
('costs','ch-extra',6,'Mehrere 10.000 CHF'),
('costs','ch-self',1,'Komplett übernommen'),
('costs','ch-self',2,'Bis 100 CHF'),
('costs','ch-self',3,'Mehrere 100 CHF'),
('costs','ch-self',4,'Mehrere 1.000 CHF'),
('costs','ch-self',5,'10.000 CHF oder mehr'),
('costs','ch-self',6,'Mehrere 10.000 CHF'),
('costs','ch-abroad',1,'Komplett übernommen'),
('costs','ch-abroad',2,'Bis 100 CHF'),
('costs','ch-abroad',3,'Mehrere 100 CHF'),
('costs','ch-abroad',4,'Mehrere 1.000 CHF'),
('costs','ch-abroad',5,'10.000 CHF oder mehr'),
('costs','ch-abroad',6,'Mehrere 10.000 CHF'),
('costs','other-self',1,'Komplett übernommen'),
('costs','other-self',2,'Bis 100 €'),
('costs','other-self',3,'Mehrere 100 €'),
('costs','other-self',4,'Mehrere 1.000 €'),
('costs','other-self',5,'10.000 € oder mehr'),
('costs','other-self',6,'Mehrere 10.000 €'),
('costs','other-abroad',1,'Komplett übernommen'),
('costs','other-abroad',2,'Bis 100 €'),
('costs','other-abroad',3,'Mehrere 100 €'),
('costs','other-abroad',4,'Mehrere 1.000 €'),
('costs','other-abroad',5,'10.000 € oder mehr'),
('costs','other-abroad',6,'Mehrere 10.000 €')
ON DUPLICATE KEY UPDATE label=VALUES(label);
