<?php
declare(strict_types=1);
function ndProviderMap(array $item, string $anchor = ''): string
{
    $points = []; $missing = 0;
    foreach ($item['providers'] as $provider) {
        if ($provider['relation_status'] === 'kandidat') continue;
        if (!is_numeric($provider['loc_lat']) || !is_numeric($provider['loc_lng']) || abs((float)$provider['loc_lat']) > 90 || abs((float)$provider['loc_lng']) > 180 || ((float)$provider['loc_lat'] === 0.0 && (float)$provider['loc_lng'] === 0.0)) { $missing++; }
        $points[] = ['lat' => is_numeric($provider['loc_lat']) ? (float)$provider['loc_lat'] : null, 'lng' => is_numeric($provider['loc_lng']) ? (float)$provider['loc_lng'] : null, 'name' => $provider['name'], 'href' => $provider['dr_id'] && in_array((int)$provider['dr_id'], LCN_PRIORITY_DOCTOR_IDS, true) ? 'arzt_detail.html?id=' . (int)$provider['dr_id'] : null, 'place' => trim($provider['loc_plz'] . ' ' . $provider['loc_city']), 'status' => $provider['relation_status'] === 'belegt' ? 'Angebot belegt' : 'Übernommene Bestandszuordnung'];
    }
    static $instance = 0;
    $mapId = 'nd-provider-map-' . ++$instance;
    $json = json_encode($points, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_UNICODE);
    return ndCard('Wo bekommst du die Behandlung?', '<div class="nd-provider-map"><p>Verknüpfte Anbieter mit gespeichertem Hauptstandort. Entfernung als Luftlinie, keine Fahrstrecke. Noch ungeprüfte Anbieter-Kandidaten sind nicht eingezeichnet.</p><div class="top-map-location-controls"><form class="nd-map-location"><label for="' . $mapId . '-input">PLZ oder Ort</label><div class="top-map-location-input-row"><input id="' . $mapId . '-input" name="location" maxlength="200" placeholder="z. B. 50667 oder Köln" autocomplete="off" required><button type="button" data-map-clear class="is-hidden" aria-label="Gespeicherten Standort entfernen">×</button><div class="top-map-location-suggestions is-hidden"></div></div><button class="top-map-location-submit" type="submit">Standort übernehmen</button></form><p>Dieser Standort wird auch auf den übrigen LCN-Seiten verwendet.</p></div><div class="top-map-panel"><button class="top-map-header" type="button" aria-expanded="true" aria-controls="' . $mapId . '-content"><span class="top-map-header-left"><span aria-hidden="true">▦</span>Karte</span><span class="top-map-chevron" aria-hidden="true">⌃</span></button><div id="' . $mapId . '-content" class="top-map-content"><div class="nd-map-canvas" aria-label="Karte der Behandlungsanbieter"></div><p class="top-map-status" data-map-status role="status">Standorte werden geladen …</p></div></div><section class="doctor-results-panel"><div class="doctor-results-header"><span class="doctor-results-header-left">▤ Anbieter</span><div class="doctor-view-switch doctor-view-switch-in-header" aria-label="Anbieteransicht wechseln"><button type="button" class="doctor-view-switch-button is-active" data-provider-view="cards" aria-pressed="true">Kacheln</button><button type="button" class="doctor-view-switch-button" data-provider-view="table" aria-pressed="false">Tabelle</button></div></div><div class="doctor-results-search-panel"><div class="doctor-results-search-row"><label class="doctor-results-search-field"><span class="doctor-results-search-label">Ärzt:in / Anbieter suchen</span><input type="search" class="doctor-results-search-input" data-provider-search placeholder="Name oder Ort eingeben"></label><label class="doctor-results-sort-field"><span class="doctor-results-search-label">Sortieren nach</span><select class="doctor-results-search-input" data-provider-sort><option value="name:asc">Name A–Z</option><option value="name:desc">Name Z–A</option><option value="distance:asc">Entfernung ↑</option><option value="distance:desc">Entfernung ↓</option></select></label></div></div><p data-provider-count role="status"></p><div class="nd-map-results"></div></section><p>' . $missing . ' weitere Anbieter ohne auswertbare Koordinaten.</p><script type="application/json" class="nd-map-data">' . $json . '</script></div>', $anchor);
}

