let reviewStatus='all',reviewType='all',allItems=[];
const filters=document.getElementById('review-filters'),typeFilters=document.getElementById('review-type-filters'),dashboard=document.getElementById('review-dashboard'),list=document.getElementById('review-list'),message=document.getElementById('review-message');
loadFragment('header-placeholder','components/header.html?v=4');loadFragment('footer-placeholder','components/footer.html');
filters.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{reviewStatus=button.dataset.status;activate(filters,button);loadReviews();}));
typeFilters.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{reviewType=button.dataset.type;activate(typeFilters,button);renderOverview();}));
loadReviews();
function activate(container,active){container.querySelectorAll('button').forEach(button=>button.classList.toggle('is-active',button===active));}
async function request(url,options={}){options.credentials='same-origin';options.headers={...(options.headers||{}),'X-LCN-Admin-Request':'1'};const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Anfrage fehlgeschlagen.');return data;}
async function loadReviews(){message.textContent='';list.innerHTML='<p class="review-empty">Vorschläge werden geladen …</p>';try{const data=await request(`api/review_submissions.php?status=${reviewStatus}`);allItems=data.items;renderOverview();}catch(error){message.textContent=error.message;list.innerHTML='';}}
function renderOverview(){const visible=allItems.filter(item=>reviewType==='all'||item.entity_type===reviewType);renderDashboard(allItems);if(!visible.length){list.innerHTML='<p class="review-empty">Keine Vorschläge in diesem Bereich.</p>';return;}if(reviewStatus!=='all'){list.innerHTML=visible.map(card).join('');bindActions();return;}const isOpen=item=>['pending','reviewing'].includes(item.review_status);const groups=[
    ['Mögliche Dubletten',item=>isOpen(item)&&item.triage_status==='possible_duplicate'],
    ['Ergänzungs- und Änderungsanträge',item=>isOpen(item)&&item.submission_kind==='change'&&item.triage_status!=='possible_duplicate'],
    ['Auffällige oder unvollständige Vorschläge',item=>isOpen(item)&&['suspicious','needs_review'].includes(item.triage_status)&&item.submission_kind!=='change'],
    ['Neue Ärzt:innen und Praxen',item=>isOpen(item)&&item.entity_type==='doctor'&&item.submission_kind==='new'&&item.triage_status==='clear'],
    ['Neue Behandlungen',item=>isOpen(item)&&item.entity_type==='treatment'&&item.submission_kind==='new'&&item.triage_status==='clear'],
    ['Bereits bearbeitet',item=>!['pending','reviewing'].includes(item.review_status)]
];const assigned=new Set();list.innerHTML=groups.map(([title,test])=>{const items=visible.filter(item=>!assigned.has(item.submission_id)&&test(item));items.forEach(item=>assigned.add(item.submission_id));return items.length?`<section class="review-group"><header><h2>${title}</h2><span>${items.length}</span></header>${items.map(card).join('')}</section>`:'';}).join('');bindActions();}
function renderDashboard(items){const open=items.filter(item=>['pending','reviewing'].includes(item.review_status));const values=[['Offen',open.length],['Mögliche Dubletten',open.filter(item=>item.triage_status==='possible_duplicate').length],['Änderungen',open.filter(item=>item.submission_kind==='change').length],['Ärzt:innen',open.filter(item=>item.entity_type==='doctor').length],['Behandlungen',open.filter(item=>item.entity_type==='treatment').length]];dashboard.innerHTML=values.map(([label,value])=>`<article><strong>${value}</strong><span>${label}</span></article>`).join('');}
function bindActions(){list.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>act(button)));}
function card(item){const p=item.payload||{},isChange=item.submission_kind==='change',triageLabel={clear:'Vorprüfung unauffällig',needs_review:'Prüfung empfohlen',possible_duplicate:'Mögliche Dublette',suspicious:'Auffällig'}[item.triage_status]||item.triage_status;const reasons=(item.triage_reasons||[]).map(reason=>`<li>${esc(reason)}</li>`).join('');const ignored=new Set(['type','existing_target_id','name','website','email','phone','confirmation']);const details=Object.entries(p).filter(([key,value])=>!ignored.has(key)&&value!==''&&value!=null&&(!Array.isArray(value)||value.length)).map(([key,value])=>`<div class="review-detail"><strong>${esc(label(key))}</strong>${esc(Array.isArray(value)?value.join(', '):value)}</div>`).join('');const targetId=item.existing_target_id||item.duplicate_target_id;const targetUrl=targetId?(item.entity_type==='doctor'?`arzt_detail.html?id=${targetId}`:`therapie_detail.html?treat_id=${targetId}`):'';const mergeButton=item.duplicate_target_id?'<button class="merge" data-action="merge">Mit bestehendem Eintrag zusammenführen</button>':'';return `<article class="review-card is-${esc(item.entity_type)}" data-id="${item.submission_id}"><div class="review-card-top"><div><span class="review-entity">${item.entity_type==='doctor'?'ÄRZT:IN / PRAXIS':'BEHANDLUNG'}</span><span class="review-kind">${isChange?'ERGÄNZUNG / ÄNDERUNG':'NEUER EINTRAG'}</span><h3>${esc(item.name)}</h3></div><span class="review-date">${esc(item.created_at)}</span></div><div class="review-triage is-${esc(item.triage_status)}"><strong>${esc(triageLabel)}</strong><span>Prüfwert ${item.triage_score}/100</span>${reasons?`<ul>${reasons}</ul>`:''}${targetUrl?`<a href="${targetUrl}" target="_blank">Bestehenden Eintrag vergleichen ↗</a>`:''}</div><div class="review-links">${item.website?`<a href="${esc(item.website)}" target="_blank" rel="noopener">Quelle öffnen ↗</a>`:'<span>Keine Website angegeben</span>'}${item.email?`<a href="mailto:${esc(item.email)}">${esc(item.email)}</a>`:''}${item.phone?`<span>${esc(item.phone)}</span>`:''}${item.city?`<span>${esc(item.city)}</span>`:''}${item.experience?`<strong>Erfahrung: ${esc(item.experience)}</strong>`:''}</div><details><summary>Alle eingereichten Angaben ansehen</summary><div class="review-details">${details||'<p>Keine weiteren Angaben.</p>'}</div></details><textarea class="review-note" placeholder="Interne Prüfnotiz">${esc(item.reviewer_note||'')}</textarea><div class="review-actions"><button data-action="reviewing">In Prüfung</button>${mergeButton}<button class="approve" data-action="approve">${isChange?'Änderungen übernehmen':'Als neuen Eintrag freigeben'}</button><button class="duplicate" data-action="duplicate">Nur als Dublette markieren</button><button class="reject" data-action="reject">Ablehnen</button></div><div class="review-current-status">Aktueller Status: ${esc(item.review_status)}</div></article>`;}
async function act(button){const reviewCard=button.closest('.review-card'),action=button.dataset.action;if(['approve','merge'].includes(action)&&!confirm(action==='merge'?'Die neuen Angaben in den erkannten bestehenden Eintrag übernehmen?':'Diesen Antrag jetzt in den Datenbestand übernehmen?'))return;reviewCard.querySelectorAll('button').forEach(item=>item.disabled=true);try{const result=await request('api/review_submissions.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({submission_id:Number(reviewCard.dataset.id),action,note:reviewCard.querySelector('.review-note').value})});message.textContent=`Antrag #${reviewCard.dataset.id}: ${statusLabel(result.status)}.`;await loadReviews();}catch(error){message.textContent=error.message;reviewCard.querySelectorAll('button').forEach(item=>item.disabled=false);}}
function statusLabel(status){return {reviewing:'in Prüfung',approved:'freigegeben',duplicate:'als Dublette markiert',rejected:'abgelehnt'}[status]||status;}
function loadFragment(id,url){fetch(url).then(response=>response.text()).then(html=>document.getElementById(id).innerHTML=html);}
function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}function label(key){return key.replaceAll('_',' ').replace(/^./,char=>char.toUpperCase());}
