(function () {
    const isDoctors=/top_behandler\.html$/i.test(location.pathname),isTreatments=/top_behandlungen\.html$/i.test(location.pathname);
    if(!isDoctors&&!isTreatments)return;
    const sharedKey='lcn_shared_location_preference',clearedKey='lcn_shared_location_cleared',germany={lat:51.1657,lng:10.4515};
    let map,markerLayer,userMarker,currentLocation,suggestionTimer,suggestionController=[];
    document.addEventListener('DOMContentLoaded',init);

    async function init(){
        const reference=document.querySelector(isDoctors?'.featured-experts':'.featured-treatments');if(!reference)return;
        const section=document.createElement('section');section.className='top-recommendation-map-section';section.innerHTML=`<div class="top-map-location-controls"><form id="top-map-location-form"><label for="top-map-location-input">Adresse oder Ort</label><div class="top-map-location-input-row"><input id="top-map-location-input" type="text" placeholder="z. B. Venloer Straße 123, Köln" autocomplete="off"><button id="top-map-location-clear" class="is-hidden" type="button" aria-label="Gespeicherten Standort entfernen">×</button><div id="top-map-location-suggestions" class="top-map-location-suggestions is-hidden" role="listbox"></div></div><button class="top-map-location-submit" type="submit">Standort übernehmen</button></form><p>Dieser Standort wird auch auf den übrigen LCN-Seiten verwendet.</p></div><div class="top-map-panel"><button id="top-map-toggle" class="top-map-header" type="button" aria-expanded="true"><span class="top-map-header-left"><span aria-hidden="true">▦</span>Karte</span><span class="top-map-chevron" aria-hidden="true">⌃</span></button><div id="top-map-content" class="top-map-content"><div id="top-recommendation-map"></div><p id="top-map-status" class="top-map-status">Standorte werden geladen …</p></div></div>`;reference.before(section);
        bindControls();restoreSharedLocation();await ensureLeaflet();initMap();await refreshMap();window.addEventListener('storage',handleStorage);
    }
    function bindControls(){const form=document.getElementById('top-map-location-form'),input=document.getElementById('top-map-location-input'),clear=document.getElementById('top-map-location-clear'),toggle=document.getElementById('top-map-toggle'),content=document.getElementById('top-map-content');form.addEventListener('submit',submitLocation);input.addEventListener('input',scheduleSuggestions);clear.addEventListener('click',clearLocation);document.addEventListener('click',event=>{if(!event.target.closest('.top-map-location-input-row'))hideSuggestions();});toggle.addEventListener('click',()=>{const collapsed=content.classList.toggle('is-collapsed');toggle.classList.toggle('is-collapsed',collapsed);toggle.setAttribute('aria-expanded',String(!collapsed));if(!collapsed)setTimeout(()=>map?.invalidateSize(),0);});}
    function restoreSharedLocation(){try{const stored=JSON.parse(localStorage.getItem(sharedKey)||'null');if(validLocation(stored)){currentLocation={lat:Number(stored.lat),lng:Number(stored.lng),label:String(stored.location||stored.label||'Gespeicherter Standort'),city:String(stored.city||'')};document.getElementById('top-map-location-input').value=currentLocation.label;}}catch(_){}updateClearButton();}
    async function submitLocation(event){event.preventDefault();const input=document.getElementById('top-map-location-input'),button=event.currentTarget.querySelector('[type="submit"]'),query=input.value.trim();if(!query)return;button.disabled=true;setStatus('Standort wird gesucht …');try{const response=await fetch(`api/geocode_location.php?q=${encodeURIComponent(query)}`),data=await response.json();if(!response.ok||!data.ok||!data.result)throw new Error('Der Standort konnte nicht gefunden werden.');setSharedLocation(data.result,query);input.value=currentLocation.label;hideSuggestions();window.dispatchEvent(new CustomEvent('homepage:location-changed'));await refreshMap();}catch(error){setStatus(error.message||'Standort konnte nicht geladen werden.',true);}finally{button.disabled=false;}}
    function setSharedLocation(location,fallback){currentLocation={lat:Number(location.lat),lng:Number(location.lng),label:String(location.formatted||location.label||fallback),city:String(location.city||'')};localStorage.setItem(sharedKey,JSON.stringify({location:currentLocation.label,label:currentLocation.label,city:currentLocation.city,lat:currentLocation.lat,lng:currentLocation.lng}));localStorage.removeItem(clearedKey);updateClearButton();}
    async function clearLocation(){currentLocation=null;document.getElementById('top-map-location-input').value='';localStorage.removeItem(sharedKey);localStorage.setItem(clearedKey,'1');updateClearButton();hideSuggestions();window.dispatchEvent(new CustomEvent('homepage:location-changed'));await refreshMap();}
    function updateClearButton(){document.getElementById('top-map-location-clear')?.classList.toggle('is-hidden',!currentLocation);}
    function scheduleSuggestions(){clearTimeout(suggestionTimer);const query=document.getElementById('top-map-location-input').value.trim();if(query.length<3){hideSuggestions();return;}suggestionTimer=setTimeout(()=>loadSuggestions(query),300);}
    async function loadSuggestions(query){suggestionController?.abort?.();suggestionController=new AbortController();try{const response=await fetch(`api/geocode_location.php?q=${encodeURIComponent(query)}`,{signal:suggestionController.signal}),data=await response.json();const results=Array.isArray(data.results)?data.results:[];const box=document.getElementById('top-map-location-suggestions');box.innerHTML=results.map((result,index)=>`<button type="button" data-index="${index}">${escapeHtml(result.formatted||'')}</button>`).join('');box.classList.toggle('is-hidden',!results.length);box.querySelectorAll('button').forEach(button=>button.addEventListener('click',async()=>{const result=results[Number(button.dataset.index)];setSharedLocation(result,result.formatted);document.getElementById('top-map-location-input').value=currentLocation.label;hideSuggestions();window.dispatchEvent(new CustomEvent('homepage:location-changed'));await refreshMap();}));}catch(error){if(error.name!=='AbortError')hideSuggestions();}}
    function hideSuggestions(){document.getElementById('top-map-location-suggestions')?.classList.add('is-hidden');}
    function handleStorage(event){if(![sharedKey,clearedKey].includes(event.key))return;currentLocation=null;restoreSharedLocation();refreshMap();}
    function initMap(){window.LCNImages?.configureLeaflet?.(L);map=L.map('top-recommendation-map',{zoomControl:false,scrollWheelZoom:false}).setView([germany.lat,germany.lng],6);const node=document.getElementById('top-recommendation-map');node.addEventListener('click',()=>{map.scrollWheelZoom.enable();node.classList.add('is-scroll-zoom-active');});node.addEventListener('mouseleave',()=>{map.scrollWheelZoom.disable();node.classList.remove('is-scroll-zoom-active');});L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles &copy; Esri &mdash; Source: Esri, OpenStreetMap-Mitwirkende und weitere'}).addTo(map);markerLayer=L.layerGroup().addTo(map);}
    async function refreshMap(){if(!map)return;setStatus('Standorte werden geladen …');try{const points=isDoctors?await loadDoctorPoints():await loadTreatmentPoints();renderPoints(points);}catch(_){setStatus('Die Standortkarte konnte gerade nicht geladen werden.',true);}}
    function renderPoints(points){markerLayer.clearLayers();if(userMarker){map.removeLayer(userMarker);userMarker=null;}const bounds=[],groups=groupPoints(points),urls=window.LCNImages?.urls||{};const providerIcon=L.icon({iconUrl:urls['map-marker-default']||'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',iconRetinaUrl:urls['map-marker-default-retina']||'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png',shadowUrl:urls['map-marker-shadow']||'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',iconSize:[25,41],iconAnchor:[12,41],popupAnchor:[1,-34],shadowSize:[41,41]});groups.forEach(group=>{bounds.push([group.lat,group.lng]);const icon=group.points.length>1?countIcon(group.points.length,urls):providerIcon;L.marker([group.lat,group.lng],{icon,riseOnHover:true}).bindPopup(buildPopup(group)).addTo(markerLayer);});if(currentLocation){const red=L.icon({iconUrl:urls['map-marker-red']||'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-red.png',shadowUrl:urls['map-marker-shadow']||'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',iconSize:[25,41],iconAnchor:[12,41],popupAnchor:[1,-34],shadowSize:[41,41]});userMarker=L.marker([currentLocation.lat,currentLocation.lng],{icon:red}).bindPopup(`<strong>Dein Standort</strong><br>${escapeHtml(currentLocation.label)}`).addTo(map);bounds.push([currentLocation.lat,currentLocation.lng]);}if(bounds.length)map.fitBounds(bounds,{padding:[28,28],maxZoom:8});else map.setView([germany.lat,germany.lng],6);setStatus(points.length?`${points.length} Einträge mit Standort auf der Karte.`:'Für diese Auswahl sind keine Einträge mit Koordinaten vorhanden.');setTimeout(()=>map.invalidateSize(),0);}
    function countIcon(count,urls){return L.divIcon({className:'top-map-count-marker',html:`<img src="${escapeHtml(urls['map-marker-default']||'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png')}" alt=""><span>${count}</span>`,iconSize:[31,41],iconAnchor:[15,41],popupAnchor:[0,-35]});}
    function groupPoints(points){const groups=new Map();points.forEach(point=>{if(!validCoordinates(point.lat,point.lng))return;const key=`${point.lat.toFixed(6)},${point.lng.toFixed(6)}`;if(!groups.has(key))groups.set(key,{lat:point.lat,lng:point.lng,points:[]});groups.get(key).points.push(point);});return [...groups.values()];}
    function buildPopup(group){const items=group.points.map(point=>`<li><a href="${escapeHtml(point.href)}">${escapeHtml(point.title)}</a>${point.subtitle?`<small>${escapeHtml(point.subtitle)}</small>`:''}</li>`).join('');return `<strong>${group.points.length>1?`${group.points.length} Einträge`:escapeHtml(group.points[0].title)}</strong>${group.points.length===1&&group.points[0].subtitle?`<br>${escapeHtml(group.points[0].subtitle)}`:''}<ul class="top-map-popup-list">${items}</ul>`;}
    async function waitForIds(selector,parameter){for(let i=0;i<30;i++){const ids=[...document.querySelectorAll(selector)].map(link=>new URL(link.href).searchParams.get(parameter)).filter(Boolean);if(ids.length)return[...new Set(ids)];await new Promise(resolve=>setTimeout(resolve,100));}return[];}
    async function loadDoctorPoints(){const ids=await waitForIds('#featured-experts-list a[href*="arzt_detail.html?id="]','id'),origin=currentLocation||germany;const response=await fetch(`api/doctors_search.php?lat=${origin.lat}&lng=${origin.lng}&radiusKm=all&includeNoCoords=0`),data=await response.json();if(!response.ok||!data.ok)throw new Error();const wanted=new Set(ids.map(Number));return(data.items||[]).filter(item=>wanted.has(Number(item.dr_id))&&validCoordinates(item.loc_lat,item.loc_lng)).map(item=>({lat:Number(item.loc_lat),lng:Number(item.loc_lng),title:item.dr_display_name,subtitle:[item.loc_plz,item.loc_city].filter(Boolean).join(' '),href:`arzt_detail.html?id=${Number(item.dr_id)}`}));}
    async function loadTreatmentPoints(){const ids=await waitForIds('#featured-treatments-list a[href*="therapie_detail.html?treat_id="]','treat_id');if(!ids.length)return[];const origin=currentLocation||germany,response=await fetch(`api/treatments_search.php?treat_ids=${encodeURIComponent(ids.join(','))}&sort=name&direction=asc&include_map=1&lat=${origin.lat}&lng=${origin.lng}`),data=await response.json();if(!response.ok||!data.ok)throw new Error();return(data.items||[]).map(item=>({item,provider:item.nearest_provider})).filter(({provider})=>provider&&validCoordinates(provider.loc_lat,provider.loc_lng)).map(({item,provider})=>({lat:Number(provider.loc_lat),lng:Number(provider.loc_lng),title:item.behandlung,subtitle:[provider.dr_display_name,provider.loc_city].filter(Boolean).join(' · '),href:`therapie_detail.html?treat_id=${Number(item.treat_id)}`}));}
    function validLocation(value){return value&&validCoordinates(value.lat,value.lng);}function validCoordinates(lat,lng){lat=Number(lat);lng=Number(lng);return Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)>.001&&Math.abs(lng)>.001&&Math.abs(lat)<=90&&Math.abs(lng)<=180;}
    function setStatus(text,error=false){const node=document.getElementById('top-map-status');if(node){node.textContent=text;node.classList.toggle('is-error',error);}}
    function ensureLeaflet(){if(window.L)return Promise.resolve();return new Promise((resolve,reject)=>{if(!document.querySelector('link[data-top-map-leaflet]')){const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';css.dataset.topMapLeaflet='1';document.head.append(css);}const existing=document.querySelector('script[data-top-map-leaflet]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return;}const script=document.createElement('script');script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';script.dataset.topMapLeaflet='1';script.onload=resolve;script.onerror=reject;document.head.append(script);});}
    function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
})();
