document.addEventListener('DOMContentLoaded', async () => {
    const accessScript=document.createElement('script');accessScript.src='scripts/access-nav.js?v=2';document.head.append(accessScript);
    const duplicateStyles=document.createElement('link');duplicateStyles.rel='stylesheet';duplicateStyles.href='styles/duplicate_check.css?v=1';document.head.append(duplicateStyles);
    const refinementStyles=document.createElement('link');refinementStyles.rel='stylesheet';refinementStyles.href='styles/entry_refinements.css?v=1';document.head.append(refinementStyles);
    const doctorNameStyles=document.createElement('link');doctorNameStyles.rel='stylesheet';doctorNameStyles.href='styles/doctor_name_fields.css?v=1';document.head.append(doctorNameStyles);
    fragment('header-placeholder', 'components/header.html?v=4');
    fragment('footer-placeholder', 'components/footer.html');
    const form = document.getElementById('entry-form');
    const message = document.getElementById('entry-message');
    enhanceEntryPage(form);
    try {
        const response = await fetch('api/submission_options.php');
        const options = await response.json();
        if (!options.ok) throw new Error();
        document.querySelectorAll('.smart-select').forEach(node => { const items=options[node.dataset.source]||[]; buildSmartSelect(node,items); if(node.dataset.source!=='specialties')enhanceSelectionViews(node,items); });
        const type = form.elements.type.value;
        buildDuplicateChecker(form, type === 'doctor' ? options.doctors : options.treatments, type);
    } catch { document.querySelectorAll('.smart-select').forEach(node => node.innerHTML = '<p class="smart-empty">Auswahlliste konnte nicht geladen werden.</p>'); }
    form.addEventListener('submit', async event => {
        event.preventDefault(); if(form.elements.type.value==='doctor'&&!composeDoctorName(form)){message.className='error';message.textContent='Bitte gib mindestens einen Vor- oder Nachnamen oder den Namen der Praxis/Einrichtung an.';return;} if (!form.reportValidity()) return;
        const button = form.querySelector('.entry-submit'); button.disabled = true; message.className = ''; message.textContent = 'Wird gespeichert …';
        try { const response = await fetch('api/create_submission.php', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(formObject(new FormData(form)))}); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || 'Speichern fehlgeschlagen.'); message.className = 'success'; message.textContent = `Danke! Vorschlag #${result.submission_id} wartet jetzt auf Prüfung.`; }
        catch (error) { message.className = 'error'; message.textContent = error.message; }
        finally { button.disabled = false; }
    });
});
function buildDuplicateChecker(form, _items, type) {
    const nameInput=form.elements.name,sourceInputs=type==='doctor'?[form.elements.title,form.elements.firstname,form.elements.lastname,form.elements.organization].filter(Boolean):[nameInput],box=document.createElement('div');box.className='duplicate-check';const anchor=type==='doctor'?form.querySelector('.doctor-name-fields'):nameInput.closest('label');anchor.after(box);let timer,requestNumber=0;
    function clear(){form.querySelector('input[name="existing_target_id"]')?.remove();box.innerHTML='';}
    sourceInputs.forEach(input=>input.addEventListener('input',()=>{if(type==='doctor')composeDoctorName(form);clearTimeout(timer);clear();const query=nameInput.value.trim();if(query.length<2)return;box.innerHTML='<div class="duplicate-none">Vorhandene Einträge werden geprüft …</div>';const current=++requestNumber;timer=setTimeout(async()=>{try{const response=await fetch(`api/submission_duplicate_search.php?type=${encodeURIComponent(type)}&q=${encodeURIComponent(query)}`,{cache:'no-store'});const result=await response.json();if(current!==requestNumber)return;if(!response.ok||!result.ok)throw new Error(result.error||'Prüfung fehlgeschlagen.');renderMatches(result.items);}catch(error){box.innerHTML=`<div class="duplicate-none is-warning">${escapeHtml(error.message)}</div>`;}},280);}));
    function renderMatches(matches){if(!matches.length){box.innerHTML='<div class="duplicate-none">✓ Kein ähnlicher vorhandener Eintrag gefunden.</div>';return;}box.innerHTML=`<strong>${matches.length} mögliche vorhandene Einträge</strong>${matches.map(item=>`<article><div><b>${escapeHtml(item.label)}</b><small>${escapeHtml(item.meta||'')}</small></div><a href="${escapeHtml(item.detail_url)}" target="_blank">Detail öffnen ↗</a><button type="button" data-existing-id="${Number(item.id)}">Diesen Eintrag ergänzen</button></article>`).join('')}`;box.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>selectExisting(matches.find(item=>String(item.id)===button.dataset.existingId))));}
    async function selectExisting(item){let hidden=form.querySelector('input[name="existing_target_id"]');if(!hidden){hidden=document.createElement('input');hidden.type='hidden';hidden.name='existing_target_id';form.append(hidden);}hidden.value=item.id;nameInput.value=item.label;box.innerHTML='<div class="duplicate-none">Aktuelle Daten werden geladen …</div>';try{const response=await fetch(`api/submission_existing_detail.php?type=${encodeURIComponent(type)}&id=${Number(item.id)}`,{cache:'no-store'});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Daten konnten nicht geladen werden.');applyExistingData(form,result.data);if(type==='doctor')composeDoctorName(form,item.label);box.innerHTML=`<div class="duplicate-selected"><strong>✓ Ergänzungs-/Änderungsantrag</strong><span>${escapeHtml(item.label)}</span><a href="${escapeHtml(item.detail_url)}" target="_blank">Aktuelle Detailseite ansehen ↗</a><button type="button">Auswahl aufheben</button></div>`;box.querySelector('button').addEventListener('click',()=>{clear();sourceInputs[0]?.focus();});}catch(error){box.innerHTML=`<div class="duplicate-none is-warning">${escapeHtml(error.message)}</div>`;}}
    const requestedId=Number(new URLSearchParams(location.search).get('existing_target_id')||0);
    if(requestedId>0){const requestedItem=_items.find(item=>Number(item.id)===requestedId);if(requestedItem)selectExisting({...requestedItem,detail_url:requestedItem.detail_url||detailUrl(type,requestedId)});else selectExisting({id:requestedId,label:type==='doctor'?'Ausgewählter Ärzt:innen-Eintrag':'Ausgewählte Behandlung',detail_url:detailUrl(type,requestedId)});}
}
function composeDoctorName(form,fallback=''){const parts=['title','firstname','lastname'].map(name=>form.elements[name]?.value.trim()).filter(Boolean);const organization=form.elements.organization?.value.trim()||'';const composed=parts.join(' ')||organization||fallback;form.elements.name.value=composed;return composed;}
function applyExistingData(form,data){Object.entries(data).forEach(([name,value])=>{if(['features','insurance','specialty_ids','treatment_ids','doctor_ids'].includes(name))return;if(name==='website'&&value&&!/^https?:\/\//i.test(String(value)))return;const field=form.elements[name];if(field&&value!=null&&String(value)!=='')field.value=value;});['features','insurance'].forEach(name=>{const selected=new Set(data[name]||[]);form.querySelectorAll(`input[name="${name}[]"]`).forEach(input=>input.checked=selected.has(input.value));});['specialty_ids','treatment_ids','doctor_ids'].forEach(name=>{const node=document.querySelector(`.smart-select[data-name="${name}"]`);if(!node)return;const selectedIds=new Set((data[name]||[]).map(String));node._selected=new Map((node._items||[]).filter(item=>selectedIds.has(String(item.id))).map(item=>[String(item.id),item.label]));renderChips(node);});}
function detailUrl(type,id){return `${type==='doctor'?'arzt_detail.html?id=':'therapie_detail.html?treat_id='}${Number(id)}`;}
function enhanceEntryPage(form){
    const type=form.elements.type.value;
    form.setAttribute('autocomplete','off');form.querySelectorAll('input,textarea').forEach(field=>{if(!['checkbox','radio','hidden'].includes(field.type)){field.setAttribute('autocomplete','off');field.setAttribute('data-1p-ignore','true');field.setAttribute('data-lpignore','true');field.setAttribute('data-bwignore','true');}});
    const website=form.elements.website;website.required=false;website.closest('label').childNodes[0].textContent=type==='doctor'?'Website oder Profil-Link (gewünscht, aber optional)':'Hauptquelle (gewünscht, aber optional)';
    if(type==='doctor'){
        form.classList.add('doctor-entry-form');
        const cardGrid=form.querySelector('.entry-card-grid'),cards=cardGrid?Array.from(cardGrid.children):[];if(cards.length>=3){const side=document.createElement('div');side.className='doctor-side-cards';side.append(cards[1],cards[2]);cardGrid.append(side);}
        const nameLabel=form.elements.name.closest('label');form.elements.name.type='hidden';form.elements.name.required=false;
        const fields=document.createElement('fieldset');fields.className='doctor-name-fields';fields.innerHTML='<legend>Name der Ärztin, des Arztes oder der Praxis *</legend><label>Titel <span>(optional)</span><input name="title" maxlength="120" placeholder="z. B. Dr. med." autocomplete="off" data-1p-ignore="true"></label><label>Vorname<input name="firstname" maxlength="120" autocomplete="off" data-1p-ignore="true"></label><label>Nachname<input name="lastname" maxlength="120" autocomplete="off" data-1p-ignore="true"></label><label>Praxis / Einrichtung<input name="organization" maxlength="255" placeholder="Falls es eine Praxis oder Klinik ist" autocomplete="off" data-1p-ignore="true"></label>';
        nameLabel.replaceWith(fields);form.prepend(form.elements.name||nameLabel.querySelector('input[name="name"]'));
        const locationContent=document.querySelectorAll('.entry-guided')[1]?.querySelector('.entry-content');
        if(locationContent){const mapWrap=document.createElement('div');mapWrap.className='entry-location-map-wrap';mapWrap.innerHTML='<div><button type="button" class="entry-map-search">Adresse auf Karte prüfen</button><p class="entry-map-status">Adresse eintragen und anschließend auf der Karte prüfen.</p></div><div id="entry-location-map" aria-label="Karte des Praxisstandorts"></div>';locationContent.append(mapWrap);mapWrap.querySelector('button').addEventListener('click',()=>geocodeEntryAddress(form,mapWrap));}
    }else{
        const source=form.elements.source_url;if(source)source.closest('label').childNodes[0].textContent='Weitere unabhängige Quelle (optional)';
        const note=form.elements.experience_note;if(note)note.placeholder='Wie hast du die Behandlung vertragen? Was wurde besser, blieb gleich oder wurde schlechter?';
        const finalIntro=document.querySelectorAll('.entry-guided aside')[4];if(finalIntro){finalIntro.querySelector('h2').textContent='Abschließende Hinweise';finalIntro.querySelector('p').textContent='Zusätzlicher Kontext für die redaktionelle Prüfung.';}
    }
}
function enhanceSelectionViews(node,items){
    const categories=new Map();items.forEach(item=>{const category=String(item.meta||'Ohne Kategorie').trim()||'Ohne Kategorie';categories.set(category,(categories.get(category)||0)+1);});
    const panel=document.createElement('div');panel.className='selection-browser';panel.innerHTML='<div class="selection-view-switch"><button type="button" class="is-active" data-view="overview">Übersicht</button><button type="button" data-view="list">Liste & Suche</button></div><div class="selection-category-overview"></div>';
    node.prepend(panel);const overview=panel.querySelector('.selection-category-overview'),control=node.querySelector('.smart-select-control');
    overview.innerHTML=[...categories].sort((a,b)=>a[0].localeCompare(b[0],'de')).map(([label,count])=>`<button type="button" data-category="${escapeHtml(label)}"><strong>${escapeHtml(label)}</strong><span>${count} Einträge</span></button>`).join('');
    control.hidden=true;panel.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
    overview.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{setView('list');const search=node.querySelector('.smart-select-search');search.value=button.dataset.category==='Ohne Kategorie'?'':button.dataset.category;search.dispatchEvent(new Event('input'));search.focus();}));
    function setView(view){panel.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('is-active',button.dataset.view===view));overview.hidden=view!=='overview';control.hidden=view!=='list';if(view==='list')node.querySelector('.smart-select-search').focus();}
}
let entryMap,entryMarker;
async function geocodeEntryAddress(form,wrap){const parts=['street','house_number','postal_code','city'].map(name=>form.elements[name]?.value.trim()).filter(Boolean);const status=wrap.querySelector('.entry-map-status');if(parts.length<2){status.textContent='Bitte mindestens Straße und Ort oder PLZ angeben.';return;}status.textContent='Standort wird gesucht …';try{const response=await fetch(`api/geocode_location.php?q=${encodeURIComponent(parts.join(' '))}`);const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'Standort nicht gefunden.');await ensureLeaflet();const result=data.result;if(!entryMap){entryMap=L.map('entry-location-map').setView([result.lat,result.lng],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap'}).addTo(entryMap);}else entryMap.setView([result.lat,result.lng],15);if(entryMarker)entryMarker.remove();entryMarker=L.marker([result.lat,result.lng]).addTo(entryMap);setHidden(form,'lat',result.lat);setHidden(form,'lng',result.lng);status.textContent=`Gefunden: ${result.formatted}`;}catch(error){status.textContent=error.message;}}
function setHidden(form,name,value){let input=form.elements[name];if(!input){input=document.createElement('input');input.type='hidden';input.name=name;form.append(input);}input.value=value;}
function ensureLeaflet(){if(window.L)return Promise.resolve();return new Promise((resolve,reject)=>{const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.append(css);const script=document.createElement('script');script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';script.onload=resolve;script.onerror=reject;document.head.append(script);});}
function buildSmartSelect(node,items){
    node.innerHTML=`<div class="smart-select-control"><input class="smart-select-search" type="search" placeholder="${escapeHtml(node.dataset.placeholder||'Suchen …')}"><button class="smart-select-toggle" type="button">⌄</button></div><div class="smart-select-menu" hidden></div><div class="smart-select-chips"></div>`;
    const search=node.querySelector('.smart-select-search'),menu=node.querySelector('.smart-select-menu');node._selected=new Map();node._items=items;
    function draw(){const query=search.value.trim().toLocaleLowerCase('de');const matches=items.filter(item=>!query||String(item.label).toLocaleLowerCase('de').includes(query)||String(item.meta||'').toLocaleLowerCase('de').includes(query)).slice(0,100);menu.innerHTML=matches.length?matches.map(item=>`<label class="smart-select-option"><input type="checkbox" value="${Number(item.id)}"><span>${escapeHtml(item.label)}</span><small>${escapeHtml(item.meta||'')}</small></label>`).join(''):'<div class="smart-empty">Kein passender Eintrag.</div>';menu.querySelectorAll('input').forEach(input=>{input.checked=node._selected.has(input.value);input.addEventListener('change',()=>{if(input.checked)node._selected.set(input.value,input.parentElement.querySelector('span').textContent);else node._selected.delete(input.value);renderChips(node);});});}
    search.addEventListener('focus',()=>{menu.hidden=false;draw();});search.addEventListener('input',draw);node.querySelector('.smart-select-toggle').addEventListener('click',()=>{menu.hidden=!menu.hidden;if(!menu.hidden)draw();});document.addEventListener('click',event=>{if(!node.contains(event.target))menu.hidden=true;});
}
function renderChips(node){const chips=node.querySelector('.smart-select-chips');chips.innerHTML=[...node._selected].map(([id,label])=>`<button type="button" class="smart-chip" data-id="${id}">${escapeHtml(label)} ×</button><input type="hidden" name="${node.dataset.name}[]" value="${id}">`).join('');chips.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{node._selected.delete(button.dataset.id);renderChips(node);}));}
function formObject(data){const out={};data.forEach((value,key)=>{const k=key.endsWith('[]')?key.slice(0,-2):key;if(key.endsWith('[]'))(out[k]||=[]).push(value);else out[k]=value;});return out;}function fragment(id,url){fetch(url).then(r=>r.text()).then(html=>document.getElementById(id).innerHTML=html);}function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}function toggleMobileMenu(){document.querySelector('.main-nav ul')?.classList.toggle('show');}
